#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 24 11:40:57 2020

@author: z003z7n
"""

class Bank:
    
    rate_of_interest = 5
    
    def __init__(self):
        pass
    
    @classmethod
    def interest_display(cls):
        print(Bank.rate_of_interest)